graspgen_server:
  ros__parameters:
    object_pointcloud_path: "/share/pcjson/example.json"
    gripper_name: "robotiq140"
    gripper_config_path: "/ros2_ws/src/GraspGen/models/checkpoints/graspgen_robotiq_2f_140.yml"
    gripper_mesh_path: "/share/tool_mesh/robotiq_140_collision.stl"
    save_results: true
    grasp_result_path: "/share/grasp_result/example_pointcloud_antipodal.yaml"
    grasp_threshold: -1.0
    num_grasps: 300
    return_topk: true
    topk_num_grasps: 10
    no_visulaization: false